// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvShkQ-dRCrZAV5U9NDvIqgWWqshr3yZs',
    appId: '1:805156752798:web:df8477f94d0ab40885da8f',
    messagingSenderId: '805156752798',
    projectId: 'finalyearproject-9a455',
    authDomain: 'finalyearproject-9a455.firebaseapp.com',
    storageBucket: 'finalyearproject-9a455.firebasestorage.app',
    measurementId: 'G-C85ZFHL88Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwc4IlTIwlRP8Wpx9lSk4UHCBfegqC69g',
    appId: '1:805156752798:android:473a22a65a3c123185da8f',
    messagingSenderId: '805156752798',
    projectId: 'finalyearproject-9a455',
    storageBucket: 'finalyearproject-9a455.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMg6UgYa-wetnrjN3QLLYcv703s-aE1oo',
    appId: '1:805156752798:ios:9f8c71990c8db56285da8f',
    messagingSenderId: '805156752798',
    projectId: 'finalyearproject-9a455',
    storageBucket: 'finalyearproject-9a455.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMg6UgYa-wetnrjN3QLLYcv703s-aE1oo',
    appId: '1:805156752798:ios:9f8c71990c8db56285da8f',
    messagingSenderId: '805156752798',
    projectId: 'finalyearproject-9a455',
    storageBucket: 'finalyearproject-9a455.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvShkQ-dRCrZAV5U9NDvIqgWWqshr3yZs',
    appId: '1:805156752798:web:b5354c9dfad5b87385da8f',
    messagingSenderId: '805156752798',
    projectId: 'finalyearproject-9a455',
    authDomain: 'finalyearproject-9a455.firebaseapp.com',
    storageBucket: 'finalyearproject-9a455.firebasestorage.app',
    measurementId: 'G-NMRZB43K0P',
  );
}
